### PR TITLE
REST Connect security scheme precedence

### PR DESCRIPTION
**Pull request by giordanolucas**

### CODE REVIEW

**Comment by wwarner-salesforce** [comment]
@mcampo , would you please confirm this small change, or delegate to someone on the Exchange team to confirm?

**Comment by wwarner-salesforce** [comment]
And @giordanolucas , thank you very much for the PR!

**Comment by mcampo** [comment]
@wwarner-salesforce this looks fine to me. Thanks, @giordanolucas for the PR!

**Review by wwarner-salesforce — APPROVED** [review]

**Review by mcampo — APPROVED** [review]
👍

**Pull request merged**
