### PR TITLE
note that Exchange 1 is an old version

### PR DESCRIPTION
**Pull request by wwarner-salesforce**
note that Exchange 1 is an old version

### CODE REVIEW

**Comment by wwarner-salesforce** [comment]
@kuntald , I was talking with Tony Li from UX about wanting to make it clearer that Exchange 2 is the current version, and the docs for Exchange 1 are separate. I know we have customers on both versions, and as I understand it Exchange 1 is not "deprecated", but is an older legacy version with some differences that are reflected in the docs. Would you please take a look at this PR and make sure it's correct?

**Review by runnabro — APPROVED** [review]

**Review by george-hoffer — COMMENTED** [review]
Please ask Kuntal to review these fixes -- I want to make sure this title change is in line with how we're positioning the transition from Exchange 1 to Exchange 2.

**Comment by wwarner-salesforce** [comment]
Certainly. I'll hold merging until Kuntal approves.

**Comment by wwarner-salesforce** [comment]
Kuntal just met with me, went over the changes, and approved them. He emphasized that as soon as we have a date for the deprecation of Exchange 1, we should add it to these docs to motivate customers to migrate.

Edited to add: He stopped back by to note that the addition should say that Exchange 1 in the cloud is deprecated at a certain date, and should not refer to Exchange 1 on-prem. Notes about Exchange 1 on-prem would be covered outside the docs, likely in the maintenance and support pages.

**Pull request merged**
