### PR TITLE
page alias

### PR DESCRIPTION
**Pull request by wwarner-salesforce**
From to-publish-an-asset.adoc to to-create-an-asset.adoc .

Goes with https://github.com/mulesoft/docs-exchange/pull/55 and should be merged after that PR.

### CODE REVIEW

**Review by fermujica — APPROVED** [review]

**Comment by fermujica** [comment]
The redirects works as expected 👍

**Comment by wwarner-salesforce** [comment]
Thank you!

**Review by fermujica — CHANGES_REQUESTED** [review]
Please fix these broken refrences:
`repo: https://github.com/mulesoft/docs-exchange | branch: page-alias | component: exchange | version: master
  path: modules/ROOT/nav.adoc | xref: to-publish-an-asset.adoc
  path: modules/ROOT/pages/about-documenting-an-api.adoc | xref: to-publish-an-asset.adoc
  path: modules/ROOT/pages/workflow-sharing-assets.adoc | xref: to-publish-an-asset.adoc`

**Comment by wwarner-salesforce** [comment]
https://github.com/mulesoft/docs-exchange/pull/55 removes the broken references from nav.adoc, about-documenting-an-api.adoc, and workflow-sharing-assets.adoc. Edited the PR title here to emphasize that this should not be merged until after PR 55.

**Review by fermujica — APPROVED** [review]

**Comment by wwarner-salesforce** [comment]
https://github.com/mulesoft/docs-exchange/pull/55 is merged. Merging this PR.

**Pull request merged**
