### PR TITLE
Maven plugin requirement

### PR DESCRIPTION
**Pull request by PabloCamino**
Due to an incompatibility uncovered on case 00255604 I decided to add this prerrequisite.

### CODE REVIEW

**Comment by marianomerlo** [comment]
Hey @PabloCamino , which version of the `org.mule.tools.maven.mule-maven-plugin` have you validated?

**Comment by PabloCamino** [comment]
This was happening with 3.3.5 reference case 00255604

**Comment by wwarner-salesforce** [comment]
@PabloCamino and @marianomerlo I'd like to merge or close this PR by the end of this week.

Is the case number a JIRA ticket such as https://www.mulesoft.org/jira/browse/SE-00255604 ? I don't see a ticket there, so either I don't have read access permission or the case is in some system other than the Jira SE project. How can I see case 00255604?

What are the remaining steps to decide what this PR should say?

**Comment by marianomerlo** [comment]
That's fine. We can go wit this.

**Review by marianomerlo — APPROVED** [review]

**Comment by wwarner-salesforce** [comment]
Thank you @marianomerlo !

**Comment by PabloCamino** [comment]
The number corresponds to a support case on the mulesoft organization
Salesforce instance.

**Review by dhirsch1 — APPROVED** [review]

**Review by dhirsch1 — APPROVED** [review]

**Pull request merged**
